# Generated by Django 5.0.2 on 2024-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_active_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
    ]
