# Generated by Django 5.0.2 on 2024-02-12 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_volunteer_is_active_member_volunteer_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='adherence_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='is_active_member',
            field=models.BooleanField(default=True),
        ),
    ]
