# Generated by Django 5.0.2 on 2024-02-12 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_volunteer_adherence_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='participation',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
